### ISSUE TITLE
KeyError: 'data'

### ISSUE THREAD

**Issue by yibai567** [ben-do/FB-GraphAPI-crawler#1]
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    crawler.get_posts(since="2016-06-07", until="2016-06-10")
  File "/alidata/www/python/FB-GraphAPI-crawler/GraphCrawler.py", line 39, in get_posts
    for d in posts["data"]:
KeyError: 'data'

**Comment by ben-do** [comment]
Try `print posts` to check if your get the right "posts" or not.
The right format should contain `data`

**Comment by RohithSml** [comment]
Its better to use pdb to better understand and debug the code, just before `for` loop type this
`import pdb; pdb.set_trace()`
run in terminal to access pdb 
check the object r by typing `dir(r)`
